#!/bin/sh

### BEGIN INIT INFO
# Provides:          BLE Scanner
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Discovers BLE Devices
# Description:       Service discovers BLE devices and writes to /tmp its presence
### END INIT INFO

DAEMON="/usr/bin/python3 /opt/ble2mqtt/ble2mqtt"
DAEMON_NAME=ble2mqtt

# Add any command line options for your daemon here
DAEMON_OPTS="--server 192.168.1.123 --name <set_name> --user <set_user> --password <set_password> --log /var/log/ble2mqtt.log --error-log /var/log/ble2mqtt-error.log"

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    sleep 60
    hciconfig hci0 down
    sleep 2
    hciconfig hci up
    sleep 1
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0
